image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Laravel
    init: |
      composer install
      cp .env.example .env
      php artisan key:generate
      touch database/database.sqlite
      sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
      sed -i '/DB_HOST/d' .env
      sed -i '/DB_PORT/d' .env
      sed -i '/DB_DATABASE/d' .env
      sed -i '/DB_USERNAME/d' .env
      sed -i '/DB_PASSWORD/d' .env
      php artisan migrate --seed
    command: |
      php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview 